config/routes.rb
Rails.application.routes.draw do
  namespace :system do
    get 'roles/index'
    get 'roles/new'
    get 'roles/edit'
  end
  devise_scope :system_user do
    get 'login' => 'system_users/sessions#new', as: :new_system_user_session
    post 'login' => 'system_users/sessions#create', as: :system_user_session
    delete 'logout' => 'system_users/sessions#destroy', as: :destroy_system_user_session
    get 'sign_up' => 'system_users/registrations#new', as: :sign_up_system_user
    post 'sign_up' => 'system_users/registrations#create', as: :register_system_user
  end
  devise_for :system_users, skip: :all

  get 'reset_password' => 'system/system_users#reset_password', as: :reset_password_system_system_user
  get 'update_password' => 'system/system_users#update_password', as: :update_password_system_system_user

  root :to => 'toppage#index'

  namespace :parent do
    resources :parents
  end

  namespace :product do
    resources :products do
      member do
        get :download
      end
    end
  end

  namespace :customer do
    resources :customers
  end

  namespace :system do
    resources :system_users
    resources :roles
  end
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ProductImageUploader

  has_many :product_details, inverse_of: :product, dependent: :destroy

  enum :category => { :outer => 1, :bottoms => 2, :shirts => 3, :cutsew => 4, :nit => 5, :goods => 6, :inner => 7 }
  enum :sex => { :gender_free => 1, :womens => 2, :mens => 3 }
  enum :status => { :disabled => 0, :normal => 1, :sale => 2, :pricedown => 3, :end => 4 }

  accepts_nested_attributes_for :product_details, :allow_destroy => true

  #バリデーション
  validates :product_div, :presence => true, :length => { :maximum => 3 }
  validates :item_cd, :presence => true, :length => { :maximum => 5 }
  validates :product_cd, :presence => true, :length => { :maximum => 8 }, :uniqueness => true
  validates :name, :presence => true, :length => { :maximum => 255 }
  validates :category, :presence => true
  validates :sex, :presence => true
  validates :status, :presence => true

  #カスタムバリデーション
  validate :sale_start_cannot_be_in_the_past
  validate :sale_end_cannot_be_before_sale_start

  def sale_start_cannot_be_in_the_past
    if sale_start.present? && sale_start < Date.today
      errors.add(:sale_start, "は過去日を指定出来ません。")
    end
  end

  def sale_end_cannot_be_before_sale_start
    if sale_end.present? && sale_start.present? && sale_end < sale_start
      errors.add(:sale_end, "は販売開始日時より過去を指定出来ません。")
    end
  end
end

app/controllers/product/products_controller.rb
class Product::ProductsController < ApplicationController
  def index
    @q = Product.ransack(params[:q])
    @products = @q.result(:distinct => true).page(params[:page] || 1)
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
    @product.product_details.build
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to :controller => "product/products", :action => "show", :id => @product.id
    else
      flash[:alert] = "商品の登録に失敗しました。"
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to :controller => "product/products", :action => "show", :id => @product.id
    else
      flash[:alert] = "商品の更新に失敗しました。"
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      redirect_to :controller => "product/products", :action => "index"
    else
      render :show
    end
  end

  def download
    @product = Product.find(params[:id])
    image = @product.image
    send_data(image.read, :filename => "download#{File.extname(image.path)}")
  end

  private def product_params
    product_detail_params = %i(
      id
      product_id
      color
      size
      season
      product_country
      scheduled_arrive
      colors
      _destroy
    )
    permitted_params = [
      :product_div,
      :item_cd,
      :product_cd,
      :name,
      :category,
      :sex,
      :status,
      :color,
      :sale_start,
      :sale_end,
      :image,
      { :product_details_attributes => product_detail_params },
    ]
    params.require(:product).permit(permitted_params)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/product/products/_product_detail_fields.html.slim
tr.nested-fields
  td = f.input :color, label: false
  td = f.input :size, label: false,
       as: :radio_buttons,
       collection: ProductDetail.sizes.keys.map{ |k| [k, ProductDetail.enum_i18n(:size, k)] },
       label_method: :second,
       value_method: :first,
       wrapper: :horizontal_collection_inline
  td = f.input :season,
       as: :select,
       collection: ProductDetail.seasons.keys.map{ |k| [k, ProductDetail.enum_i18n(:season, k)] },
       label_method: :second,
       value_method: :first,
       label: false,
       include_blank: "選択して下さい"
  td = f.input :product_country,
       as: :select,
       collection: ProductDetail.product_countries.keys.map{ |k| [k, ProductDetail.enum_i18n(:product_country, k)] },
       label_method: :second,
       value_method: :first,
       label: false,
       include_blank: "選択して下さい"
  td = f.input :scheduled_arrive, label: false, html5: true, wrapper: :horizontal_multi_select
  td = link_to_remove_association "削除", f ,class: 'btn btn-default'

app/views/product/products/_search_form.html.slim
.row
  .col-md-12
    .card.card-primary
      .card-header
        h3.card-title
          | 商品検索
      = form_with scope: :q, method: :get, local: true, class: 'form-horizontal' do |f|
        .card-body
          .form-group.row
            = f.label Product.human_attribute_name(:name), class: 'col-sm-2 col-form-label'
            .col-sm-10
              = f.text_field :parent_no_eq, class: 'form-control'
          .form-group.row
            = f.label '商品コード', class: 'col-sm-2 col-form-label'
            .col-sm-10
              = f.text_field :child_child_name_eq, class: 'form-control'
        .card-footer.text-right
          = f.submit "検索", class: "button btn btn-default"

app/views/product/products/edit.html.slim
.wrapper
  = render 'layouts/navbar'
  = render 'layouts/sidemenu'
  .content-wrapper
    section.content-header
      .container-fluid
        .row.mb-2
          .col-sm-6
            h1 商品編集
    section.content
      .container-fluid
        = simple_form_for @product, url: product_product_path, method: :put, wrapper: :horizontal_form do |f|
          .row
            .col-md-12
              .card.card-primary
                .card-header
                  h3.card-title 商品編集
                .card-body
                  = f.input :image, as: :file, wrapper: :horizontal_file
                  = f.input :product_div,
                    as: :select,
                    collection: ProductConst.product_divison,
                    label_method: :const_cd_text,
                    value_method: :const_cd,
                    include_blank: "選択して下さい",
                    required: true
                  = f.input :item_cd
                  = f.input :product_cd
                  = f.input :name
                  = f.input :category,
                    as: :select,
                    collection: Product.categories.keys.map{ |k| [k, Product.enum_i18n(:category, k)] },
                    label_method: :second,
                    value_method: :first,
                    include_blank: "選択して下さい"
                  = f.input :sex,
                    as: :select,
                    collection: Product.sexes.keys.map{ |k| [k, Product.enum_i18n(:sex, k)] },
                    label_method: :second,
                    value_method: :first,
                    include_blank: "選択して下さい"
                  = f.input :status,
                    as: :radio_buttons,
                    collection: Product.statuses.keys.map{ |k| [k, Product.enum_i18n(:status, k)] },
                    label_method: :second,
                    value_method: :first,
                    wrapper: :horizontal_collection_inline
                  = f.input :sale_start, html5: true, wrapper: :horizontal_multi_select
                  = f.input :sale_end, html5: true, wrapper: :horizontal_multi_select
              .card.card-primary
                .card-header
                  h3.card-title 商品詳細
                .card-body.p-0
                  table.table.table-hover.table-sm#detail-association-insertion-product-detail
                    thead.thead-default
                      tr
                        th 色
                        th サイズ
                        th シーズン
                        th 生産国
                        th 入荷予定日
                        th 削除
                    tbody
                      = f.simple_fields_for :product_details do |d|
                        = render partial: 'product_detail_fields', locals: { f: d }
                  .card-footer.text-right
                    = link_to_add_association '商品詳細を追加する', f, :product_details,
                      class: 'btn btn-default',
                      data: { association_insertion_node: '#detail-association-insertion-product-detail', association_insertion_method: 'append' }
              = f.submit class: "button btn btn-primary float-right", data: { confirm: t('confirmation.create') }
        .row
          .col-md-12
            = link_to '戻る', product_products_path, class: 'btn btn-default'

app/views/product/products/index.html.slim
.wrapper
  = render 'layouts/navbar'
  = render 'layouts/sidemenu'
  .content-wrapper
    .content-header
      .container-fluid
        .row.mb-2
          .col-sm-6
            h1.m-0.text-dark
              | 商品管理画面
    .content
      .container-fluid
        = render 'search_form'
        = link_to '新規登録', new_product_product_path, class: 'btn btn-default mb-3'
        .row
          .col-lg-12
            .card
              .card-header
                h3.card-title
                  | 商品一覧
              table.table.table-hover
                thead.thead-default
                  tr
                    th = Product.human_attribute_name(:name)
                    th 商品画像
                    th 商品コード
                    th 商品名
                    th 分類
                    th 性別
                    th ステータス
                    th 販売期限
                  tbody
                  - if @products
                    - @products.each do |product|
                      tr
                        td = link_to product.id, product_product_path(product.id)
                        td
                          - if product.image.present?
                            = image_tag product.image.thumb.url
                          - else
                            = '画像無し'
                        td = product.product_cd
                        td = product.name
                        td = product.category_label
                        td = product.sex_label
                        td = product.status_label
                        td = product.sale_period
  aside.control-sidebar.control-sidebar-dark
    .p-3
      h5
        | Title
      p
        | Sidebar content
  = render 'layouts/footer'

app/views/product/products/new.html.slim
.wrapper
  = render 'layouts/navbar'
  = render 'layouts/sidemenu'
  .content-wrapper
    section.content-header
      .container-fluid
        .row.mb-2
          .col-sm-6
            h1 商品新規登録
    section.content
      .container-fluid
        = simple_form_for @product, url: product_products_path, wrapper: :horizontal_form do |f|
          .row
            .col-md-12
              .card.card-primary
                .card-header
                  h3.card-title 商品新規登録
                .card-body
                  = f.input :image, as: :file, wrapper: :horizontal_file
                  = f.input :product_div,
                    as: :select,
                    collection: ProductConst.product_divison,
                    label_method: :const_cd_text,
                    value_method: :const_cd,
                    include_blank: "選択して下さい",
                    required: true
                  = f.input :item_cd
                  = f.input :product_cd
                  = f.input :name
                  = f.input :category,
                    as: :select,
                    collection: Product.categories.keys.map{ |k| [k, Product.enum_i18n(:category, k)] },
                    label_method: :second,
                    value_method: :first,
                    include_blank: "選択して下さい"
                  = f.input :sex,
                    as: :select,
                    collection: Product.sexes.keys.map{ |k| [k, Product.enum_i18n(:sex, k)] },
                    label_method: :second,
                    value_method: :first,
                    include_blank: "選択して下さい"
                  = f.input :status,
                    as: :radio_buttons,
                    collection: Product.statuses.keys.map{ |k| [k, Product.enum_i18n(:status, k)] },
                    label_method: :second,
                    value_method: :first,
                    wrapper: :horizontal_collection_inline
                  = f.input :sale_start, html5: true, wrapper: :horizontal_multi_select
                  = f.input :sale_end, html5: true, wrapper: :horizontal_multi_select
              .card.card-primary
                .card-header
                  h3.card-title 商品詳細
                .card-body.p-0
                  table.table.table-hover.table-sm#detail-association-insertion-product-detail
                    thead.thead-default
                      tr
                        th 色
                        th サイズ
                        th シーズン
                        th 生産国
                        th 入荷予定日
                        th 削除
                    tbody
                      = f.simple_fields_for :product_details do |d|
                        = render partial: 'product_detail_fields', locals: { f: d }
                  .card-footer.text-right
                    = link_to_add_association '商品詳細を追加する', f, :product_details,
                      class: 'btn btn-default',
                      data: { association_insertion_node: '#detail-association-insertion-product-detail', association_insertion_method: 'append' }
              = f.submit class: "button btn btn-primary float-right", data: { confirm: t('confirmation.create') }
        .row
          .col-md-12
            = link_to '戻る', product_products_path, class: 'btn btn-default'

app/views/product/products/show.html.slim
.wrapper
  = render 'layouts/navbar'
  = render 'layouts/sidemenu'
  .content-wrapper
    section.content-header
      .container-fluid
        .row.mb-2
          .col-sm-6
            h1 商品管理
    section.content
      .container-fluid
        .row
          .col-md-12
            .card.card-primary
              .card-header
                h3.card-title 商品詳細
              .card-body
                dl.row
                  - if @product.image.present?
                    dt.col-sm-3.text-right 画像
                    dd.col-sm-9
                      = link_to 'ダウンロード', download_product_product_path(@product), class: 'btn btn-sm btn-default mb-2'
                    dt.col-sm-3
                    dd.col-sm-9
                      = image_tag @product.image_url, class: 'img-thumbnail'
                  dt.col-sm-3.text-right = Product.human_attribute_name(:id)
                  dd.col-sm-9 = @product.id
                  dt.col-sm-3.text-right = Product.human_attribute_name(:name)
                  dd.col-sm-9 = @product.name
                  dt.col-sm-3.text-right = Product.human_attribute_name(:product_div)
                  dd.col-sm-9 = @product.product_div
                  dt.col-sm-3.text-right = Product.human_attribute_name(:item_product_cd)
                  dd.col-sm-9 = @product.item_cd + @product.product_cd
                  dt.col-sm-3.text-right = Product.human_attribute_name(:category)
                  d.col-sm-9 = @product.category_label
                  dt.col-sm-3.text-right = Product.human_attribute_name(:sex)
                  dd.col-sm-9 = @product.sex_label
                  dt.col-sm-3.text-right = Product.human_attribute_name(:status)
                  dd.col-sm-9 = @product.status_label
                  dt.col-sm-3.text-right = ProductDetail.human_attribute_name(:color)
                  - colors = @product.product_details.map { |product_detail| product_detail.color}
                  dd.col-sm-9 = colors.uniq.join(',')
                  dt.col-sm-3.text-right = ProductDetail.human_attribute_name(:size)
                  - sizes = @product.product_details.map { |product_detail| product_detail.size_label}
                  dd.col-sm-9 = sizes.join(',')
                  dt.col-sm-3.text-right = ProductDetail.human_attribute_name(:season)
                  - seasons = @product.product_details.map { |product_detail| product_detail.season_label}
                  dd.col-sm-9 = seasons.uniq.join(',')
              .card-footer.text-right
                = link_to '編集', edit_product_product_path, class: 'btn btn-default mr-3'
                = link_to '削除', product_product_path(@product.id), method: :delete, class: 'btn btn-danger', data: { confirm: '削除しますか?' }
        .row
          .col-md-12
            = link_to '戻る', product_products_path, class: 'btn btn-default mb-3 mr-3'
  = render 'layouts/footer'