config/routes.rb
Rails.application.routes.draw do
  namespace :system do
    get 'roles/index'
    get 'roles/new'
    get 'roles/edit'
  end
  devise_scope :system_user do
    get 'login' => 'system_users/sessions#new', as: :new_system_user_session
    post 'login' => 'system_users/sessions#create', as: :system_user_session
    delete 'logout' => 'system_users/sessions#destroy', as: :destroy_system_user_session
    get 'sign_up' => 'system_users/registrations#new', as: :sign_up_system_user
    post 'sign_up' => 'system_users/registrations#create', as: :register_system_user
  end
  devise_for :system_users, skip: :all

  get 'reset_password' => 'system/system_users#reset_password', as: :reset_password_system_system_user
  get 'update_password' => 'system/system_users#update_password', as: :update_password_system_system_user

  root :to => 'toppage#index'

  namespace :parent do
    resources :parents
  end

  namespace :product do
    resources :products do
      member do
        get :download
      end
    end
  end

  namespace :customer do
    resources :customers
  end

  namespace :system do
    resources :system_users
    resources :roles
  end
end

app/models/system_user.rb
class SystemUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :authentication_keys => [:login_id]

  enum :admin => { :admin => true, :general => false }

  has_many :system_users_roles,  dependent: :destroy
  has_many :roles, through: :system_users_roles, source: :role
end

app/controllers/system/roles_controller.rb
class System::RolesController < ApplicationController

  # before_action :authorize_role, only: %i(index new create)

  def index
    @q = Role.ransack(params[:q])
    @roles = @q.result.page(params[:page])
  end

  def new
    @role = Role.new
    @role.roles_permissions.build
  end

  def create
    @role = Role.create(role_params)
    if @role.save
      redirect_to :controller => "system/roles", :action => "index"
    else
      render :new
    end
  end

  def edit
    set_role
    @role.roles_permissions
  end

  def update
    set_role
    if @role.update(role_params)
      redirect_to :controller => "system/roles", :action => "index"
    else
      render :edit
    end
  end

  def destroy
    set_role
    if @role.destroy
      redirect_to :controller => "system/roles", :action => "index"
    else
      render :edit
    end
  end

  private def authorize_role
    # authorize Role
  end

  private def set_role
    @role = Role.find(params[:id])
    # authorize @role
  end

  private def role_params
    params.require(:role).permit(:id, :name, permission_ids: [])
  end
end

app/controllers/system/system_users_controller.rb
module System
  class SystemUsersController < ApplicationController
    #before_action :authorize_system_user, only: %i(index new create)

    def index
      @q = SystemUser.ransack(params[:q])
      @system_users = @q.result.page(params[:page] || 1)
    end

    def new
      @system_user = SystemUser.new
      @system_user.system_users_roles.build
    end

    def create
      @system_user = SystemUser.new(system_user_params)
      if @system_user.save
        redirect_to :controller => "system/system_users", :action => "index"
      else
        render :new
      end
    end

    def edit
      load_system_user
    end

    def update
      load_system_user
      @system_user.attributes = system_user_params
      if @system_user.update(system_user_params)
        redirect_to :controller => "system/system_users", :action => "index"
      else
        render :edit
      end
    end

    def destroy
      load_system_user
      if @system_user.destroy
        redirect_to :controller => "system/system_users", :action => "index"
      else
        render :edit
      end
    end

    # private def authorize_system_user
    #   authorize SystemUser
    # end

    private def load_system_user
      @system_user = SystemUser.find(params[:id])
      #authorize @system_user
    end

    private def system_user_params
      permit_params = %i(id login_id name admin)
      if params[:system_user][:password].present?
        permit_params << :password
        permit_params << :password_confirmation
      end
      params.require(:system_user).permit(permit_params, role_ids: [])
    end
  end
end

app/controllers/system_users/registrations_controller.rb
# frozen_string_literal: true

class SystemUsers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
#  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  #POST /resource
  def create
   super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  #protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
   devise_parameter_sanitizer.permit(:sign_up, keys: [:login_id, :name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  #def configure_account_update_params
  #  devise_parameter_sanitizer.permit(:account_update, keys: [:user_id, :name])
  #end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/system_users/sessions_controller.rb
# frozen_string_literal: true

class SystemUsers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/system/roles_helper.rb
module System::RolesHelper
end

app/views/system/system_users/_search_form.html.slim
.row
  .col-md-12
    .card.card-secondary
      .card-header
        h3.card-title 管理ユーザ検索
      = search_form_for @q, url: system_system_users_path, wrapper: :horizontal_search_form do |f|
        .card-body
          = f.input :id_start, label: SystemUser.human_attribute_name(:id), required: false
          = f.input :name_cont, label: SystemUser.human_attribute_name(:name), required: false
        .card-footer.text-right
          = f.submit class: 'btn btn-default'

app/views/system/system_users/edit.html.slim
.wrapper
  = render 'layouts/navbar'
  = render 'layouts/sidemenu'
  .content-wrapper
    section.content-header
      .container-fluid
        .row.mb-2
          .col-sm-6
            h1 システムユーザ管理
    section.content
      .container-fluid
        .row
          .col-md-12
            .card.card-secondary
              .card-header
                h3.card-title システムユーザ編集
              = simple_form_for @system_user, url: system_system_user_path, wrapper: :horizontal_form do |f|
                = f.hidden_field :id
                = f.hidden_field :login_id
                .card-body
                  = f.input :name
                  = f.input :password
                  = f.input :password_confirmation
                  = f.input :admin, as: :radio_buttons, collection: SystemUser.admins.keys.map(&:to_sym), wrapper: :horizontal_collection_inline, required: true
                  = f.input :role_ids, as: :check_boxes, collection: Role.all, label_method: :name, value_method: :id, label: '権限',wrapper: :horizontal_collection_inline
                .card-footer.text-right
                  = f.button :submit, class: 'btn btn-primary', data: { confirm: t('confirmation.create') }
        .row
          .col-md-12
            = link_to '戻る', system_system_users_path, class: 'btn btn-default mb-3'
  = render 'layouts/footer'

app/views/system/system_users/index.html.slim
.wrapper
  = render 'layouts/navbar'
  = render 'layouts/sidemenu'
  .content-wrapper
    section.content-header
      .container-fluid
        .row.mb-2
          .col-sm-6
            h1 システムユーザ管理
    section.content
      .container-fluid
        = render 'search_form'
        .row
          .col-md-12
            .card
              .card-header
                h3.card-title システムユーザ一覧
                .card-tools
                  /= paginate @system_users
              .card-body.p-0
                table.table.table-sm
                  thead
                    tr
                      th = SystemUser.human_attribute_name(:id)
                      th = SystemUser.human_attribute_name(:name)
                      th ユーザタイプ
                  tbody
                    - @system_users.each do |system_user|
                      tr
                        td = link_to system_user.id, edit_system_system_user_path(id: system_user.id)
                        td = system_user.name
                        td = system_user.admin_label
        .row
          .col-md-12.text-right
            = link_to '新規登録', new_system_system_user_path, class: 'btn btn-default mb-3'
  = render 'layouts/footer'

app/views/system/system_users/new.html.slim
.wrapper
  = render 'layouts/navbar'
  = render 'layouts/sidemenu'
  .content-wrapper
    section.content-header
      .container-fluid
        .row.mb-2
          .col-sm-6
            h1 システムユーザ管理
    section.content
      .container-fluid
        .row
          .col-md-12
            .card.card-secondary
              .card-header
                h3.card-title システムユーザ新規登録
              = simple_form_for @system_user, url: system_system_users_path, wrapper: :horizontal_form do |f|
                .card-body
                  = f.input :login_id
                  = f.input :name
                  = f.input :password
                  = f.input :password_confirmation
                  = f.input :admin,
                    as: :radio_buttons,
                    collection: SystemUser.admins.keys.map(&:to_sym),
                    wrapper: :horizontal_collection_inline,
                    required: true
                  = f.input :role_ids, as: :check_boxes, collection: Role.all, label_method: :name, value_method: :id, label: '権限',wrapper: :horizontal_collection_inline
                .card-footer.text-right
                  = f.button :submit, class: 'btn btn-primary', data: { confirm: t('confirmation.create') }
        .row
          .col-md-12
            = link_to '戻る', system_system_users_path, class: 'btn btn-default mb-3'
  = render 'layouts/footer'