config/routes.rb
Rails.application.routes.draw do
  namespace :system do
    get 'roles/index'
    get 'roles/new'
    get 'roles/edit'
  end
  devise_scope :system_user do
    get 'login' => 'system_users/sessions#new', as: :new_system_user_session
    post 'login' => 'system_users/sessions#create', as: :system_user_session
    delete 'logout' => 'system_users/sessions#destroy', as: :destroy_system_user_session
    get 'sign_up' => 'system_users/registrations#new', as: :sign_up_system_user
    post 'sign_up' => 'system_users/registrations#create', as: :register_system_user
  end
  devise_for :system_users, skip: :all

  get 'reset_password' => 'system/system_users#reset_password', as: :reset_password_system_system_user
  get 'update_password' => 'system/system_users#update_password', as: :update_password_system_system_user

  root :to => 'toppage#index'

  namespace :parent do
    resources :parents
  end

  namespace :product do
    resources :products do
      member do
        get :download
      end
    end
  end

  namespace :customer do
    resources :customers
  end

  namespace :system do
    resources :system_users
    resources :roles
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :system_users_roles, dependent: :destroy
  has_many :roles_permissions, dependent: :destroy
  has_many :permissions, through: :roles_permissions, source: :permission

  validates :name, length: { maximum: 255 }
end

app/controllers/system/roles_controller.rb
class System::RolesController < ApplicationController

  # before_action :authorize_role, only: %i(index new create)

  def index
    @q = Role.ransack(params[:q])
    @roles = @q.result.page(params[:page])
  end

  def new
    @role = Role.new
    @role.roles_permissions.build
  end

  def create
    @role = Role.create(role_params)
    if @role.save
      redirect_to :controller => "system/roles", :action => "index"
    else
      render :new
    end
  end

  def edit
    set_role
    @role.roles_permissions
  end

  def update
    set_role
    if @role.update(role_params)
      redirect_to :controller => "system/roles", :action => "index"
    else
      render :edit
    end
  end

  def destroy
    set_role
    if @role.destroy
      redirect_to :controller => "system/roles", :action => "index"
    else
      render :edit
    end
  end

  private def authorize_role
    # authorize Role
  end

  private def set_role
    @role = Role.find(params[:id])
    # authorize @role
  end

  private def role_params
    params.require(:role).permit(:id, :name, permission_ids: [])
  end
end

app/controllers/system/system_users_controller.rb
module System
  class SystemUsersController < ApplicationController
    #before_action :authorize_system_user, only: %i(index new create)

    def index
      @q = SystemUser.ransack(params[:q])
      @system_users = @q.result.page(params[:page] || 1)
    end

    def new
      @system_user = SystemUser.new
      @system_user.system_users_roles.build
    end

    def create
      @system_user = SystemUser.new(system_user_params)
      if @system_user.save
        redirect_to :controller => "system/system_users", :action => "index"
      else
        render :new
      end
    end

    def edit
      load_system_user
    end

    def update
      load_system_user
      @system_user.attributes = system_user_params
      if @system_user.update(system_user_params)
        redirect_to :controller => "system/system_users", :action => "index"
      else
        render :edit
      end
    end

    def destroy
      load_system_user
      if @system_user.destroy
        redirect_to :controller => "system/system_users", :action => "index"
      else
        render :edit
      end
    end

    # private def authorize_system_user
    #   authorize SystemUser
    # end

    private def load_system_user
      @system_user = SystemUser.find(params[:id])
      #authorize @system_user
    end

    private def system_user_params
      permit_params = %i(id login_id name admin)
      if params[:system_user][:password].present?
        permit_params << :password
        permit_params << :password_confirmation
      end
      params.require(:system_user).permit(permit_params, role_ids: [])
    end
  end
end

app/helpers/system/roles_helper.rb
module System::RolesHelper
end

app/views/system/roles/_search_form.html.slim
.row
  .col-md-12
    .card.card-secondary
      .card-header
        h3.card-title 権限検索
      = search_form_for @q, url: system_roles_path, wrapper: :horizontal_search_form do |f|
        .card-body
          = f.input :name_start, label: Role.human_attribute_name(:name), required: false
        .card-footer.text-center
          = f.submit class: 'btn btn-default'

app/views/system/roles/edit.html.slim
.wrapper
  = render 'layouts/navbar'
  = render 'layouts/sidemenu'
  .content-wrapper
    section.content-header
      .container-fluid
        .row.mb-2
          .col-sm-6
            h1 ロール管理
    section.content
      .container-fluid
        = simple_form_for @role, url: system_role_path(@role), method: :put, wrapper: :horizontal_form do |f|
          .row
            .col-md-12
              .card.card-secondary
                .card-header
                  h3.card-title ロール編集
                .card-body
                = f.input :name
                hr
                = f.input :permission_ids,
                  as: :check_boxes,
                  collection: Permission.product_permission.map { |product_permission| [product_permission.name.slice(5..), product_permission.id]},
                  label: '製品管理',
                  wrapper: :horizontal_collection_inline
                hr
                = f.input :permission_ids,
                  as: :check_boxes,
                  collection: Permission.customer_permission.map { |customer_permission| [customer_permission.name.slice(5..), customer_permission.id]},
                  label: '顧客管理',
                  wrapper: :horizontal_collection_inline
                .card-footer.text-right
                  = link_to '削除', system_role_path(@role), class: 'btn btn-danger mr-2', method: :delete, data: { confirm: t('confirmation.destroy') }
                  = f.submit class: 'btn btn-primary', data: { confirm: t('confirmation.update') }
        .row
          .col-md-12
            = link_to '戻る', system_roles_path, class: 'btn btn-default mb-3'

app/views/system/roles/index.html.slim
.wrapper
  = render 'layouts/navbar'
  = render 'layouts/sidemenu'
  .content-wrapper
    section.content-header
      .container-fluid
        .row.mb-2
          .col-sm-6
            h1 ロール管理
    section.content
      .container-fluid
        = render 'search_form'
        .row
          .col-md-12
            .card
              .card-header
                h3.card-title 権限一覧
                .card-tools
                  = paginate @roles
              .card-body.p-0
                table.table.table-sm
                  thead
                    tr
                      th = Role.human_attribute_name(:name)
                  tbody
                    - @roles.each do |role|
                      tr
                        td = link_to role.name, edit_system_role_path(id: role.id)
        .row
          .col-md-12.text-right
            = link_to '新規登録', new_system_role_path, class: 'btn btn-default mb-3'

app/views/system/roles/new.html.slim
.wrapper
  = render 'layouts/navbar'
  = render 'layouts/sidemenu'
  .content-wrapper
    section.content-header
      .container-fluid
        .row.mb-2
          .col-sm-6
            h1 ロール管理
    section.content
      .container-fluid
        = simple_form_for @role, url: system_roles_path, wrapper: :horizontal_form do |f|
          .row
            .col-md-12
              .card.card-secondary
                .card-header
                  h3.card-title ロール新規登録
                .card-body
                = f.input :name
                hr
                = f.input :permission_ids,
                  as: :check_boxes,
                  collection: Permission.product_permission.map { |product_permission| [product_permission.name.slice(5..), product_permission.id]},
                  label: '製品管理',
                  wrapper: :horizontal_collection_inline
                hr
                = f.input :permission_ids,
                  as: :check_boxes,
                  collection: Permission.customer_permission.map { |customer_permission| [customer_permission.name.slice(5..), customer_permission.id]},
                  label: '顧客管理',
                  wrapper: :horizontal_collection_inline
                .card-footer.text-right
                  = f.submit class: 'btn btn-primary', data: { confirm: t('confirmation.create') }
        .row
          .col-md-12
            = link_to '戻る', system_roles_path, class: 'btn btn-default mb-3'