config/routes.rb
Rails.application.routes.draw do
  namespace :system do
    get 'roles/index'
    get 'roles/new'
    get 'roles/edit'
  end
  devise_scope :system_user do
    get 'login' => 'system_users/sessions#new', as: :new_system_user_session
    post 'login' => 'system_users/sessions#create', as: :system_user_session
    delete 'logout' => 'system_users/sessions#destroy', as: :destroy_system_user_session
    get 'sign_up' => 'system_users/registrations#new', as: :sign_up_system_user
    post 'sign_up' => 'system_users/registrations#create', as: :register_system_user
  end
  devise_for :system_users, skip: :all

  get 'reset_password' => 'system/system_users#reset_password', as: :reset_password_system_system_user
  get 'update_password' => 'system/system_users#update_password', as: :update_password_system_system_user

  root :to => 'toppage#index'

  namespace :parent do
    resources :parents
  end

  namespace :product do
    resources :products do
      member do
        get :download
      end
    end
  end

  namespace :customer do
    resources :customers
  end

  namespace :system do
    resources :system_users
    resources :roles
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def enum_i18n(enum_name)
    return nil if send(enum_name).nil?

    I18n.t!("enums.#{model_name.i18n_key}.#{enum_name}.#{send(enum_name)}")
  end

  def self.enums_i18n(enum_name)
    send(enum_name.to_s.pluralize).transform_keys do |key|
      I18n.t!("enums.#{model_name.i18n_key}.#{enum_name}.#{key}")
    end
  end

  def self.enum_i18n(enum_name, enum_value)
    I18n.t!("enums.#{model_name.i18n_key}.#{enum_name}.#{enum_value}")
  end
end

app/models/child.rb
class  Child < ApplicationRecord
  belongs_to :parent
  has_many :grand_children, :foreign_key => :child_no, :primary_key => :child_no
end

app/models/customer.rb
class Customer < ApplicationRecord
  scope :search_tel, lambda { |tel|
    if tel.include?("-")
      where("REPLACE(tel, '-', '') = ?", tel.delete("-"))
    else
      where("REPLACE(tel, '-', '') = ?", tel)
    end
  }

  def self.ransackable_scopes(_auth_object = nil)
    %i[search_tel]
  end
end

app/models/grand_child.rb
class GrandChild < ApplicationRecord
  belongs_to :child, :foreign_key => :child_no, :primary_key => :child_no
end

app/models/parent.rb
class Parent < ApplicationRecord
  has_many :child
end

app/models/permission.rb
class Permission < ApplicationRecord
  has_many :roles_permissions
  validates :name, length: { maximum: 255 }, presence: true
  validates :en_name, length: { maximum: 255 }, presence: true, uniqueness: { case_sensitive: true }

  scope :product_permission,
        -> {
          where(en_name: ['product_reference',
                          'product_create',
                          'product_update',
                          'product_delete'])
        }
  scope :customer_permission,
        -> {
          where(en_name: ['customer_reference',
                          'customer_create',
                          'customer_update',
                          'customer_delete'])
        }
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ProductImageUploader

  has_many :product_details, inverse_of: :product, dependent: :destroy

  enum :category => { :outer => 1, :bottoms => 2, :shirts => 3, :cutsew => 4, :nit => 5, :goods => 6, :inner => 7 }
  enum :sex => { :gender_free => 1, :womens => 2, :mens => 3 }
  enum :status => { :disabled => 0, :normal => 1, :sale => 2, :pricedown => 3, :end => 4 }

  accepts_nested_attributes_for :product_details, :allow_destroy => true

  #バリデーション
  validates :product_div, :presence => true, :length => { :maximum => 3 }
  validates :item_cd, :presence => true, :length => { :maximum => 5 }
  validates :product_cd, :presence => true, :length => { :maximum => 8 }, :uniqueness => true
  validates :name, :presence => true, :length => { :maximum => 255 }
  validates :category, :presence => true
  validates :sex, :presence => true
  validates :status, :presence => true

  #カスタムバリデーション
  validate :sale_start_cannot_be_in_the_past
  validate :sale_end_cannot_be_before_sale_start

  def sale_start_cannot_be_in_the_past
    if sale_start.present? && sale_start < Date.today
      errors.add(:sale_start, "は過去日を指定出来ません。")
    end
  end

  def sale_end_cannot_be_before_sale_start
    if sale_end.present? && sale_start.present? && sale_end < sale_start
      errors.add(:sale_end, "は販売開始日時より過去を指定出来ません。")
    end
  end
end

app/models/product_const.rb
class ProductConst < ApplicationRecord
  scope :product_divison, -> { where(:const_div => "P0001").order(:sort_no) }
  scope :color, -> { where(:const_div => "P0003").order(:sort_no) }
end

app/models/product_detail.rb
class ProductDetail < ApplicationRecord
  belongs_to :product

  enum size: { S: 1, M: 2, L: 3, XL: 4 }
  enum season: { spring: 1, summer: 2, autumn: 3, winter: 4 }
  enum product_country: { Japan: 0, China: 1, Bangladesh: 2 }
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :system_users_roles, dependent: :destroy
  has_many :roles_permissions, dependent: :destroy
  has_many :permissions, through: :roles_permissions, source: :permission

  validates :name, length: { maximum: 255 }
end

app/models/roles_permission.rb
class RolesPermission < ApplicationRecord
  belongs_to :role
  belongs_to :permission
end

app/models/system_user.rb
class SystemUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :authentication_keys => [:login_id]

  enum :admin => { :admin => true, :general => false }

  has_many :system_users_roles,  dependent: :destroy
  has_many :roles, through: :system_users_roles, source: :role
end

app/models/system_users_role.rb
class SystemUsersRole < ApplicationRecord
  belongs_to :system_user
  belongs_to :role
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_system_user!
  include Pundit

  def after_sign_out_path_for(resource_or_scope)
    new_system_user_session_path
  end

  # 例外処理
  rescue_from StandardError, with: :render_500
  rescue_from Pundit::NotAuthorizedError, with: :render_403
  rescue_from ActiveRecord::RecordNotFound, with: :render_404

  private def render_403(error)
    render 'errors/403', status: :not_found
  end

  private def render_404(error)
    render template: 'errors/404', status: :not_found
  end

  private def render_500(error)
    render template: 'errors/500', status: :internal_server_error
  end
end

app/controllers/toppage_controller.rb
class ToppageController < ApplicationController
  
  def index
    if params[:search]
      @q = Parent.ransack(params[:search])
      @parents = @q.result(:distinct => true)
    else
      @parents = nil
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/toppage_helper.rb
module ToppageHelper
end

app/views/layouts/_footer.html.slim
footer.main-footer
  .float-right.d-none.d-sm-inline
    |  Anything you want
    = link_to destroy_system_user_session_path, method: :delete, class: 'btn-sm btn-default'
        | ログアウト
  strong
    | Copyright © 2020
    a[href="https://otapedia.org"]
      | otapedia
    | .
  |  All rights reserved.

app/views/layouts/_navbar.html.slim
nav.main-header.navbar.navbar-expand.navbar-white.navbar-light
  ul.navbar-nav
    li.nav-item
      a.nav-link[data-widget="pushmenu" href="#" role="button"]
        i.fas.fa-bars
        

app/views/layouts/_sidemenu.html.slim
aside.main-sidebar.sidebar-dark-primary.elevation-4
  a.brand-link[href="/"]
    span.brand-text.font-weight-light
      | Rails 勉強部屋
      p
        = current_system_user.name
  .sidebar
    nav.mt-2
      ul.nav.nav-pills.nav-flat.nav-sidebar.nav-child-indent.flex-column[data-widget="treeview" role="menu" data-accordion="false"]
        li.nav-item.has-treeview.menu-open
          li.nav-item.has-treeview
            a.nav-link[href="#"]
              i.fa.fa-shopping-cart.nav-icon
              p
                | Ransack
                i.fa.fa-angle-left.right
            ul.nav.nav-treeview
              li.nav-item
                = link_to parent_parents_path, class: "nav-link"
                  i.far.fa-circle.nav-icon
                  p 親子孫
          li.nav-item.has-treeview
            a.nav-link[href="#"]
              i.fa.fa-box.nav-icon
              p
                | 製品管理
                i.fa.fa-angle-left.right
            ul.nav.nav-treeview
              li.nav-item
                = link_to product_products_path, class: "nav-link"
                  i.fab.fa-product-hunt.nav-icon
                  p 商品管理
          li.nav-item.has-treeview
            a.nav-link[href="#"]
              i.fas.fa-user-circle.nav-icon
              p
                | 顧客管理
                i.fa.fa-angle-left.right
            ul.nav.nav-treeview
              li.nav-item
                = link_to customer_customers_path, class: "nav-link"
                  i.fab.fa-product-hunt.nav-icon
                  p 会員管理
          li.nav-item.has-treeview
            a.nav-link[href="#"]
              i.fa.fa-cog.nav-icon
              p
                | システム管理
                i.fa.fa-angle-left.right
            ul.nav.nav-treeview
              li.nav-item
                = link_to system_system_users_path, class: "nav-link"
                  i.fas.fa-user-cog.nav-icon
                  p ユーザ管理
              li.nav-item
                = link_to system_roles_path, class: "nav-link"
                  i.fas.fa-user-cog.nav-icon
                  p ロール管理

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Study
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    link[href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet"]
  body
  - if notice
    .notice
      = notice
  - if alert
    .alert
      = alert
  = yield